import { Database, Workflow, MessageSquare, Globe, LayoutDashboard, BrainCircuit } from 'lucide-react';
import type { ServicePageData } from './ServicePage';

export const servicesData: Record<string, ServicePageData> = {
  'extracao-de-dados': {
    icon: Database,
    titlePt: 'Extração de Dados',
    titleEn: 'Data Extraction',
    subtitlePt: 'Informação é poder. Nós entregamos ela pronta.',
    subtitleEn: 'Information is power. We deliver it ready.',
    descPt: 'Coletamos, cruzamos e organizamos dados de qualquer fonte pública ou privada — Receita Federal, Google Maps, LinkedIn, marketplaces, portais governamentais e muito mais. Entregamos bases limpas, estruturadas e prontas para prospecção comercial, análise de mercado e tomada de decisão.',
    descEn: 'We collect, cross-reference and organize data from any public or private source — government databases, Google Maps, LinkedIn, marketplaces, government portals and more. We deliver clean, structured databases ready for commercial prospecting, market analysis and decision-making.',
    benefitsPt: [
      { title: 'Bases sob medida', desc: 'Dados filtrados exatamente pelo perfil que você precisa — região, setor, porte, situação fiscal.' },
      { title: 'Cruzamento inteligente', desc: 'Combinamos múltiplas fontes para enriquecer cada registro com telefone, sócios, CNAE e mais.' },
      { title: 'Atualização periódica', desc: 'Bases atualizadas mensalmente para que seus dados nunca fiquem defasados.' },
      { title: 'Entrega organizada', desc: 'Arquivos limpos em CSV, Excel ou direto no seu CRM. Pronto para uso imediato.' },
      { title: 'Volume massivo', desc: 'Processamos milhões de registros com rapidez e precisão.' },
      { title: 'Total conformidade', desc: 'Trabalhamos exclusivamente com dados públicos e em conformidade com a LGPD.' },
    ],
    benefitsEn: [
      { title: 'Custom databases', desc: 'Data filtered exactly by the profile you need — region, sector, size, fiscal status.' },
      { title: 'Intelligent cross-referencing', desc: 'We combine multiple sources to enrich each record with phone, partners, CNAE and more.' },
      { title: 'Periodic updates', desc: 'Databases updated monthly so your data never becomes outdated.' },
      { title: 'Organized delivery', desc: 'Clean files in CSV, Excel or directly into your CRM. Ready for immediate use.' },
      { title: 'Massive volume', desc: 'We process millions of records with speed and precision.' },
      { title: 'Full compliance', desc: 'We work exclusively with public data and in compliance with LGPD.' },
    ],
    sectorsPt: ['Contabilidade', 'Advocacia', 'Imobiliárias', 'Consultorias', 'Seguradoras', 'Saúde', 'Varejo', 'Indústria', 'Tecnologia', 'Financeiro'],
    sectorsEn: ['Accounting', 'Law firms', 'Real estate', 'Consulting', 'Insurance', 'Healthcare', 'Retail', 'Manufacturing', 'Technology', 'Finance'],
    ctaPt: 'Precisa de uma base de dados personalizada?',
    ctaEn: 'Need a custom database?',
  },

  'automacao': {
    icon: Workflow,
    titlePt: 'Automação de Processos',
    titleEn: 'Process Automation',
    subtitlePt: 'Menos trabalho manual. Mais tempo para o que importa.',
    subtitleEn: 'Less manual work. More time for what matters.',
    descPt: 'Automatizamos tarefas repetitivas, fluxos de aprovação, envios de e-mail, geração de relatórios, conciliações financeiras e integrações entre sistemas. Sua operação funciona no piloto automático enquanto você foca em crescer.',
    descEn: 'We automate repetitive tasks, approval workflows, email sending, report generation, financial reconciliations and system integrations. Your operation runs on autopilot while you focus on growing.',
    benefitsPt: [
      { title: 'Fluxos inteligentes', desc: 'Automações que conectam seus sistemas e eliminam retrabalho entre equipes.' },
      { title: 'Integração total', desc: 'Conectamos ERPs, CRMs, bancos, Google Sheets, WhatsApp e qualquer API.' },
      { title: 'Relatórios automáticos', desc: 'Geração e envio de relatórios sem intervenção humana.' },
      { title: 'Alertas e notificações', desc: 'Avisos automáticos por email, WhatsApp ou Slack quando algo precisa de atenção.' },
      { title: 'Escalabilidade', desc: 'Automações que crescem com o seu negócio sem precisar contratar mais gente.' },
      { title: 'ROI mensurável', desc: 'Acompanhamos as horas economizadas e o impacto financeiro direto.' },
    ],
    benefitsEn: [
      { title: 'Smart workflows', desc: 'Automations that connect your systems and eliminate rework between teams.' },
      { title: 'Full integration', desc: 'We connect ERPs, CRMs, banks, Google Sheets, WhatsApp and any API.' },
      { title: 'Automatic reports', desc: 'Report generation and delivery without human intervention.' },
      { title: 'Alerts & notifications', desc: 'Automatic alerts via email, WhatsApp or Slack when something needs attention.' },
      { title: 'Scalability', desc: 'Automations that grow with your business without hiring more people.' },
      { title: 'Measurable ROI', desc: 'We track hours saved and direct financial impact.' },
    ],
    sectorsPt: ['Escritórios contábeis', 'Financeiro', 'RH', 'Logística', 'E-commerce', 'Saúde', 'Jurídico', 'Marketing', 'Educação'],
    sectorsEn: ['Accounting firms', 'Finance', 'HR', 'Logistics', 'E-commerce', 'Healthcare', 'Legal', 'Marketing', 'Education'],
    ctaPt: 'Quer automatizar sua operação?',
    ctaEn: 'Want to automate your operation?',
  },

  'chatbots': {
    icon: MessageSquare,
    titlePt: 'Chatbots Inteligentes',
    titleEn: 'Smart Chatbots',
    subtitlePt: 'Atendimento 24h que entende, responde e resolve.',
    subtitleEn: '24/7 support that understands, responds and resolves.',
    descPt: 'Criamos assistentes virtuais com inteligência artificial para WhatsApp, sites e redes sociais. Eles entendem contexto, respondem com naturalidade, qualificam leads, agendam reuniões e resolvem dúvidas — tudo sem intervenção humana.',
    descEn: 'We create AI-powered virtual assistants for WhatsApp, websites and social media. They understand context, respond naturally, qualify leads, schedule meetings and resolve questions — all without human intervention.',
    benefitsPt: [
      { title: 'WhatsApp com IA', desc: 'Chatbot que conversa naturalmente pelo WhatsApp Business e qualifica leads automaticamente.' },
      { title: 'Atendimento 24/7', desc: 'Seus clientes são atendidos a qualquer hora, sem filas e sem espera.' },
      { title: 'Qualificação de leads', desc: 'O bot identifica o perfil do cliente e encaminha apenas os mais qualificados.' },
      { title: 'Agendamento automático', desc: 'Integração com Google Calendar para marcação de reuniões sem troca de mensagens.' },
      { title: 'Base de conhecimento', desc: 'O chatbot é treinado com informações do seu negócio para respostas precisas.' },
      { title: 'Escalação inteligente', desc: 'Quando necessário, a conversa é transferida para um humano com todo o contexto.' },
    ],
    benefitsEn: [
      { title: 'WhatsApp with AI', desc: 'Chatbot that naturally converses via WhatsApp Business and automatically qualifies leads.' },
      { title: '24/7 support', desc: 'Your customers are served at any time, without queues or waiting.' },
      { title: 'Lead qualification', desc: 'The bot identifies the customer profile and forwards only the most qualified.' },
      { title: 'Automatic scheduling', desc: 'Integration with Google Calendar for meeting booking without message exchanges.' },
      { title: 'Knowledge base', desc: 'The chatbot is trained with your business information for accurate responses.' },
      { title: 'Smart escalation', desc: 'When needed, the conversation is transferred to a human with full context.' },
    ],
    sectorsPt: ['Clínicas e consultórios', 'Imobiliárias', 'E-commerce', 'Restaurantes', 'Academias', 'Escritórios', 'Educação', 'Varejo'],
    sectorsEn: ['Clinics', 'Real estate', 'E-commerce', 'Restaurants', 'Gyms', 'Offices', 'Education', 'Retail'],
    ctaPt: 'Quer um assistente virtual para seu negócio?',
    ctaEn: 'Want a virtual assistant for your business?',
  },

  'sites': {
    icon: Globe,
    titlePt: 'Sites & Landing Pages',
    titleEn: 'Websites & Landing Pages',
    subtitlePt: 'Sua presença digital com design que converte.',
    subtitleEn: 'Your digital presence with design that converts.',
    descPt: 'Desenvolvemos sites institucionais e landing pages com design exclusivo, velocidade de carregamento máxima e otimizados para aparecer no Google. Nada de templates genéricos — cada projeto é único e pensado para converter visitantes em clientes.',
    descEn: 'We develop institutional websites and landing pages with exclusive design, maximum loading speed and optimized to rank on Google. No generic templates — each project is unique and designed to convert visitors into clients.',
    benefitsPt: [
      { title: 'Design exclusivo', desc: 'Cada site é criado do zero, alinhado à identidade visual da sua marca.' },
      { title: 'Velocidade máxima', desc: 'Sites ultrarrápidos que carregam em menos de 2 segundos.' },
      { title: 'SEO otimizado', desc: 'Estrutura e conteúdo pensados para ranquear nas primeiras posições do Google.' },
      { title: 'Mobile first', desc: 'Design responsivo que funciona perfeitamente em qualquer dispositivo.' },
      { title: 'Formulários inteligentes', desc: 'Captação de leads com formulários que integram diretamente com seu CRM ou WhatsApp.' },
      { title: 'Painel de gestão', desc: 'Atualize textos, fotos e informações sem precisar de um programador.' },
    ],
    benefitsEn: [
      { title: 'Exclusive design', desc: 'Each site is built from scratch, aligned with your brand identity.' },
      { title: 'Maximum speed', desc: 'Ultra-fast sites that load in under 2 seconds.' },
      { title: 'Optimized SEO', desc: 'Structure and content designed to rank in Google\'s top positions.' },
      { title: 'Mobile first', desc: 'Responsive design that works perfectly on any device.' },
      { title: 'Smart forms', desc: 'Lead capture with forms that integrate directly with your CRM or WhatsApp.' },
      { title: 'Management panel', desc: 'Update texts, photos and information without needing a developer.' },
    ],
    sectorsPt: ['Restaurantes', 'Clínicas', 'Escritórios', 'Lojas', 'Academias', 'Salões de beleza', 'Construtoras', 'Startups', 'Profissionais liberais'],
    sectorsEn: ['Restaurants', 'Clinics', 'Offices', 'Shops', 'Gyms', 'Beauty salons', 'Construction', 'Startups', 'Freelancers'],
    ctaPt: 'Quer um site que realmente converte?',
    ctaEn: 'Want a website that really converts?',
  },

  'dashboards': {
    icon: LayoutDashboard,
    titlePt: 'Dashboards & BI',
    titleEn: 'Dashboards & BI',
    subtitlePt: 'Seus números em tempo real, de forma visual e clara.',
    subtitleEn: 'Your numbers in real time, visually and clearly.',
    descPt: 'Criamos painéis interativos que transformam dados complexos em visualizações claras e acionáveis. Acompanhe vendas, finanças, operações e KPIs do seu negócio em tempo real, de qualquer dispositivo.',
    descEn: 'We create interactive panels that transform complex data into clear, actionable visualizations. Track sales, finances, operations and KPIs of your business in real time, from any device.',
    benefitsPt: [
      { title: 'Visão em tempo real', desc: 'Dados atualizados automaticamente para decisões rápidas e precisas.' },
      { title: 'Design intuitivo', desc: 'Painéis visuais que qualquer pessoa da equipe consegue entender.' },
      { title: 'Múltiplas fontes', desc: 'Conectamos dados de planilhas, ERPs, bancos, APIs e sistemas legados.' },
      { title: 'Alertas automáticos', desc: 'Notificações quando indicadores saem da faixa esperada.' },
      { title: 'Acesso mobile', desc: 'Consulte seus dados de qualquer lugar, no celular ou tablet.' },
      { title: 'Relatórios exportáveis', desc: 'Exporte relatórios em PDF ou Excel para apresentações e reuniões.' },
    ],
    benefitsEn: [
      { title: 'Real-time view', desc: 'Automatically updated data for fast and accurate decisions.' },
      { title: 'Intuitive design', desc: 'Visual panels that anyone on the team can understand.' },
      { title: 'Multiple sources', desc: 'We connect data from spreadsheets, ERPs, banks, APIs and legacy systems.' },
      { title: 'Automatic alerts', desc: 'Notifications when indicators go out of expected range.' },
      { title: 'Mobile access', desc: 'Check your data from anywhere, on phone or tablet.' },
      { title: 'Exportable reports', desc: 'Export reports in PDF or Excel for presentations and meetings.' },
    ],
    sectorsPt: ['Financeiro', 'Varejo', 'Logística', 'Marketing', 'Saúde', 'Indústria', 'Contabilidade', 'Educação'],
    sectorsEn: ['Finance', 'Retail', 'Logistics', 'Marketing', 'Healthcare', 'Manufacturing', 'Accounting', 'Education'],
    ctaPt: 'Quer ver seus dados de forma clara?',
    ctaEn: 'Want to see your data clearly?',
  },

  'consultoria-ia': {
    icon: BrainCircuit,
    titlePt: 'Consultoria em IA',
    titleEn: 'AI Consulting',
    subtitlePt: 'Estratégia para implementar IA onde realmente importa.',
    subtitleEn: 'Strategy to implement AI where it really matters.',
    descPt: 'Fazemos um diagnóstico completo da sua operação para identificar onde a inteligência artificial pode gerar mais impacto. Criamos um roadmap prático, selecionamos as ferramentas certas e implementamos soluções sob medida — sem hype, com resultado.',
    descEn: 'We perform a complete diagnosis of your operation to identify where artificial intelligence can generate the most impact. We create a practical roadmap, select the right tools and implement tailored solutions — no hype, just results.',
    benefitsPt: [
      { title: 'Diagnóstico operacional', desc: 'Mapeamos seus processos e identificamos gargalos e oportunidades de automação.' },
      { title: 'Roadmap de IA', desc: 'Plano prático com prioridades, cronograma e investimento estimado.' },
      { title: 'Seleção de ferramentas', desc: 'Escolhemos as melhores tecnologias para cada caso, sem viés de fornecedor.' },
      { title: 'Implementação guiada', desc: 'Acompanhamos a implementação do início ao fim com suporte técnico contínuo.' },
      { title: 'Treinamento de equipe', desc: 'Capacitamos seu time para operar e evoluir as soluções com autonomia.' },
      { title: 'Métricas de resultado', desc: 'Definimos KPIs claros para medir o retorno real de cada implementação.' },
    ],
    benefitsEn: [
      { title: 'Operational diagnosis', desc: 'We map your processes and identify bottlenecks and automation opportunities.' },
      { title: 'AI roadmap', desc: 'Practical plan with priorities, timeline and estimated investment.' },
      { title: 'Tool selection', desc: 'We choose the best technologies for each case, without vendor bias.' },
      { title: 'Guided implementation', desc: 'We follow the implementation from start to finish with continuous technical support.' },
      { title: 'Team training', desc: 'We enable your team to operate and evolve solutions autonomously.' },
      { title: 'Result metrics', desc: 'We define clear KPIs to measure the real return of each implementation.' },
    ],
    sectorsPt: ['Qualquer setor', 'Escritórios', 'Indústria', 'Varejo', 'Saúde', 'Financeiro', 'Logística', 'Educação', 'Startups'],
    sectorsEn: ['Any industry', 'Offices', 'Manufacturing', 'Retail', 'Healthcare', 'Finance', 'Logistics', 'Education', 'Startups'],
    ctaPt: 'Quer descobrir como IA pode ajudar seu negócio?',
    ctaEn: 'Want to discover how AI can help your business?',
  },
};
