import { Database, Workflow, MessageSquare, Globe, LayoutDashboard, BrainCircuit } from 'lucide-react';
import type { ServicePageData } from './ServicePage';

export const servicesData: Record<string, ServicePageData> = {
  'extracao-de-dados': {
    icon: Database,
    titlePt: 'Extração de Dados',
    titleEn: 'Data Extraction',
    subtitlePt: 'Informação é poder. Nós entregamos ela pronta.',
    subtitleEn: 'Information is power. We deliver it ready.',
    descPt: 'Coletamos, cruzamos e organizamos dados de qualquer fonte pública ou privada — Receita Federal, Google Maps, LinkedIn, marketplaces, portais governamentais e muito mais. Entregamos bases limpas, estruturadas e prontas para prospecção comercial, análise de mercado e tomada de decisão.',
    descEn: 'We collect, cross-reference and organize data from any public or private source — government databases, Google Maps, LinkedIn, marketplaces, government portals and more. We deliver clean, structured databases ready for commercial prospecting, market analysis and decision-making.',
    benefitsPt: [
      { title: 'Bases sob medida', desc: 'Dados filtrados exatamente pelo perfil que você precisa — região, setor, porte, situação fiscal.' },
      { title: 'Cruzamento inteligente', desc: 'Combinamos múltiplas fontes para enriquecer cada registro com telefone, sócios, CNAE e mais.' },
      { title: 'Atualização periódica', desc: 'Bases atualizadas mensalmente para que seus dados nunca fiquem defasados.' },
      { title: 'Entrega organizada', desc: 'Arquivos limpos em CSV, Excel ou direto no seu CRM. Pronto para uso imediato.' },
      { title: 'Volume massivo', desc: 'Processamos milhões de registros com rapidez e precisão.' },
      { title: 'Total conformidade', desc: 'Trabalhamos exclusivamente com dados públicos e em conformidade com a LGPD.' },
    ],
    benefitsEn: [
      { title: 'Custom databases', desc: 'Data filtered exactly by the profile you need — region, sector, size, fiscal status.' },
      { title: 'Intelligent cross-referencing', desc: 'We combine multiple sources to enrich each record with phone, partners, CNAE and more.' },
      { title: 'Periodic updates', desc: 'Databases updated monthly so your data never becomes outdated.' },
      { title: 'Organized delivery', desc: 'Clean files in CSV, Excel or directly into your CRM. Ready for immediate use.' },
      { title: 'Massive volume', desc: 'We process millions of records with speed and precision.' },
      { title: 'Full compliance', desc: 'We work exclusively with public data and in compliance with LGPD.' },
    ],
    sectorsPt: ['Contabilidade', 'Advocacia', 'Imobiliárias', 'Consultorias', 'Seguradoras', 'Saúde', 'Varejo', 'Indústria', 'Tecnologia', 'Financeiro'],
    sectorsEn: ['Accounting', 'Law firms', 'Real estate', 'Consulting', 'Insurance', 'Healthcare', 'Retail', 'Manufacturing', 'Technology', 'Finance'],
    ctaPt: 'Precisa de uma base de dados personalizada?',
    ctaEn: 'Need a custom database?',
    metricsPt: [
      { value: '900k+', label: 'Registros processados' },
      { value: '10+', label: 'Fontes de dados' },
      { value: '< 48h', label: 'Tempo de entrega' },
      { value: '100%', label: 'Conformidade LGPD' },
    ],
    metricsEn: [
      { value: '900k+', label: 'Records processed' },
      { value: '10+', label: 'Data sources' },
      { value: '< 48h', label: 'Delivery time' },
      { value: '100%', label: 'LGPD compliant' },
    ],
    processPt: [
      { title: 'Briefing', desc: 'Definimos juntos o perfil dos dados: região, setor, porte, filtros específicos.' },
      { title: 'Coleta', desc: 'Extraímos dados de fontes públicas e privadas com tecnologia proprietária.' },
      { title: 'Tratamento', desc: 'Limpamos, cruzamos e enriquecemos cada registro automaticamente.' },
      { title: 'Entrega', desc: 'Você recebe a base pronta em CSV, Excel ou direto no seu CRM.' },
    ],
    processEn: [
      { title: 'Briefing', desc: 'We define together the data profile: region, sector, size, specific filters.' },
      { title: 'Collection', desc: 'We extract data from public and private sources with proprietary technology.' },
      { title: 'Processing', desc: 'We clean, cross-reference and enrich each record automatically.' },
      { title: 'Delivery', desc: 'You receive the database ready in CSV, Excel or directly into your CRM.' },
    ],
    plansPt: [
      { name: 'Pontual', subtitle: 'Uma extração sob demanda', price: 'R$ 497', period: 'por extração', features: ['Até 10.000 registros', 'Filtros por região e setor', 'Entrega em CSV/Excel', 'Dados de contato + CNPJ', 'Suporte por WhatsApp'] },
      { name: 'Recorrente', subtitle: 'Base atualizada mensalmente', price: 'R$ 897', period: '/mês', features: ['Até 50.000 registros/mês', 'Atualização automática mensal', 'Cruzamento de múltiplas fontes', 'Enriquecimento com sócios e CNAE', 'Entrega em CSV, Excel ou CRM', 'Suporte prioritário'], highlight: true },
      { name: 'Enterprise', subtitle: 'Volume ilimitado + API', price: 'Sob consulta', period: '', features: ['Volume ilimitado', 'API de acesso em tempo real', 'Integração direta com seu sistema', 'Dashboards de monitoramento', 'Gerente de conta dedicado', 'SLA de entrega garantido'] },
    ],
    plansEn: [
      { name: 'One-time', subtitle: 'A single on-demand extraction', price: 'R$ 497', period: 'per extraction', features: ['Up to 10,000 records', 'Region and sector filters', 'CSV/Excel delivery', 'Contact data + tax ID', 'WhatsApp support'] },
      { name: 'Recurring', subtitle: 'Monthly updated database', price: 'R$ 897', period: '/month', features: ['Up to 50,000 records/month', 'Automatic monthly updates', 'Multi-source cross-referencing', 'Enrichment with partners and industry codes', 'CSV, Excel or CRM delivery', 'Priority support'], highlight: true },
      { name: 'Enterprise', subtitle: 'Unlimited volume + API', price: 'Custom', period: '', features: ['Unlimited volume', 'Real-time API access', 'Direct integration with your system', 'Monitoring dashboards', 'Dedicated account manager', 'Guaranteed delivery SLA'] },
    ],
  },

  'automacao': {
    icon: Workflow,
    titlePt: 'Automação de Processos',
    titleEn: 'Process Automation',
    subtitlePt: 'Menos trabalho manual. Mais tempo para o que importa.',
    subtitleEn: 'Less manual work. More time for what matters.',
    descPt: 'Automatizamos tarefas repetitivas, fluxos de aprovação, envios de e-mail, geração de relatórios, conciliações financeiras e integrações entre sistemas. Sua operação funciona no piloto automático enquanto você foca em crescer.',
    descEn: 'We automate repetitive tasks, approval workflows, email sending, report generation, financial reconciliations and system integrations. Your operation runs on autopilot while you focus on growing.',
    benefitsPt: [
      { title: 'Fluxos inteligentes', desc: 'Automações que conectam seus sistemas e eliminam retrabalho entre equipes.' },
      { title: 'Integração total', desc: 'Conectamos ERPs, CRMs, bancos, Google Sheets, WhatsApp e qualquer API.' },
      { title: 'Relatórios automáticos', desc: 'Geração e envio de relatórios sem intervenção humana.' },
      { title: 'Alertas e notificações', desc: 'Avisos automáticos por email, WhatsApp ou Slack quando algo precisa de atenção.' },
      { title: 'Escalabilidade', desc: 'Automações que crescem com o seu negócio sem precisar contratar mais gente.' },
      { title: 'ROI mensurável', desc: 'Acompanhamos as horas economizadas e o impacto financeiro direto.' },
    ],
    benefitsEn: [
      { title: 'Smart workflows', desc: 'Automations that connect your systems and eliminate rework between teams.' },
      { title: 'Full integration', desc: 'We connect ERPs, CRMs, banks, Google Sheets, WhatsApp and any API.' },
      { title: 'Automatic reports', desc: 'Report generation and delivery without human intervention.' },
      { title: 'Alerts & notifications', desc: 'Automatic alerts via email, WhatsApp or Slack when something needs attention.' },
      { title: 'Scalability', desc: 'Automations that grow with your business without hiring more people.' },
      { title: 'Measurable ROI', desc: 'We track hours saved and direct financial impact.' },
    ],
    sectorsPt: ['Escritórios contábeis', 'Financeiro', 'RH', 'Logística', 'E-commerce', 'Saúde', 'Jurídico', 'Marketing', 'Educação'],
    sectorsEn: ['Accounting firms', 'Finance', 'HR', 'Logistics', 'E-commerce', 'Healthcare', 'Legal', 'Marketing', 'Education'],
    ctaPt: 'Quer automatizar sua operação?',
    ctaEn: 'Want to automate your operation?',
    metricsPt: [
      { value: '200+', label: 'Horas economizadas/mês' },
      { value: '70%', label: 'Menos retrabalho' },
      { value: '∞', label: 'Integrações possíveis' },
      { value: '< 7d', label: 'Primeira entrega' },
    ],
    metricsEn: [
      { value: '200+', label: 'Hours saved/month' },
      { value: '70%', label: 'Less rework' },
      { value: '∞', label: 'Possible integrations' },
      { value: '< 7d', label: 'First delivery' },
    ],
    processPt: [
      { title: 'Mapeamento', desc: 'Identificamos os processos repetitivos e gargalos da sua operação.' },
      { title: 'Arquitetura', desc: 'Desenhamos o fluxo de automação e integrações necessárias.' },
      { title: 'Desenvolvimento', desc: 'Construímos e testamos cada automação com validações semanais.' },
      { title: 'Ativação', desc: 'Colocamos em produção, treinamos a equipe e monitoramos.' },
    ],
    processEn: [
      { title: 'Mapping', desc: 'We identify repetitive processes and bottlenecks in your operation.' },
      { title: 'Architecture', desc: 'We design the automation flow and required integrations.' },
      { title: 'Development', desc: 'We build and test each automation with weekly validations.' },
      { title: 'Activation', desc: 'We deploy, train the team and monitor.' },
    ],
    plansPt: [
      { name: 'Pontual', subtitle: 'Uma automação específica', price: 'A partir de R$ 1.500', period: 'por projeto', features: ['1 processo automatizado', 'Integração com seus sistemas', 'Documentação completa', 'Suporte por 30 dias', 'Treinamento da equipe'] },
      { name: 'Operação', subtitle: 'Automação contínua do setor', price: 'Sob consulta', period: 'projeto + mensalidade', features: ['Múltiplos processos automatizados', 'Integrações ilimitadas', 'Relatórios e alertas automáticos', 'Redução real de carga operacional', 'Suporte prioritário', 'Manutenção e evolução mensal'], highlight: true },
      { name: 'Scale', subtitle: 'Operação no piloto automático', price: 'R$ 2.997', period: '/mês', features: ['Fluxos ilimitados', 'Dashboards de monitoramento', 'IA embarcada nos fluxos', 'Integrações customizadas', 'Gerente de conta dedicado', 'SLA de uptime 99.9%'] },
    ],
    plansEn: [
      { name: 'One-time', subtitle: 'A specific automation', price: 'From R$ 1,500', period: 'per project', features: ['1 automated process', 'Integration with your systems', 'Complete documentation', '30-day support', 'Team training'] },
      { name: 'Operations', subtitle: 'Continuous sector automation', price: 'Custom quote', period: 'project + monthly', features: ['Multiple automated processes', 'Unlimited integrations', 'Reports and automatic alerts', 'Real operational load reduction', 'Priority support', 'Monthly maintenance and evolution'], highlight: true },
      { name: 'Scale', subtitle: 'Operation on autopilot', price: 'R$ 2,997', period: '/month', features: ['Unlimited workflows', 'Monitoring dashboards', 'AI embedded in workflows', 'Custom integrations', 'Dedicated account manager', '99.9% uptime SLA'] },
    ],
  },

  'chatbots': {
    icon: MessageSquare,
    titlePt: 'Chatbots Inteligentes',
    titleEn: 'Smart Chatbots',
    subtitlePt: 'Atendimento 24h que entende, responde e resolve.',
    subtitleEn: '24/7 support that understands, responds and resolves.',
    descPt: 'Criamos assistentes virtuais com inteligência artificial para WhatsApp, sites e redes sociais. Eles entendem contexto, respondem com naturalidade, qualificam leads, agendam reuniões e resolvem dúvidas — tudo sem intervenção humana.',
    descEn: 'We create AI-powered virtual assistants for WhatsApp, websites and social media. They understand context, respond naturally, qualify leads, schedule meetings and resolve questions — all without human intervention.',
    benefitsPt: [
      { title: 'WhatsApp com IA', desc: 'Chatbot que conversa naturalmente pelo WhatsApp Business e qualifica leads automaticamente.' },
      { title: 'Atendimento 24/7', desc: 'Seus clientes são atendidos a qualquer hora, sem filas e sem espera.' },
      { title: 'Qualificação de leads', desc: 'O bot identifica o perfil do cliente e encaminha apenas os mais qualificados.' },
      { title: 'Agendamento automático', desc: 'Integração com Google Calendar para marcação de reuniões sem troca de mensagens.' },
      { title: 'Base de conhecimento', desc: 'O chatbot é treinado com informações do seu negócio para respostas precisas.' },
      { title: 'Escalação inteligente', desc: 'Quando necessário, a conversa é transferida para um humano com todo o contexto.' },
    ],
    benefitsEn: [
      { title: 'WhatsApp with AI', desc: 'Chatbot that naturally converses via WhatsApp Business and automatically qualifies leads.' },
      { title: '24/7 support', desc: 'Your customers are served at any time, without queues or waiting.' },
      { title: 'Lead qualification', desc: 'The bot identifies the customer profile and forwards only the most qualified.' },
      { title: 'Automatic scheduling', desc: 'Integration with Google Calendar for meeting booking without message exchanges.' },
      { title: 'Knowledge base', desc: 'The chatbot is trained with your business information for accurate responses.' },
      { title: 'Smart escalation', desc: 'When needed, the conversation is transferred to a human with full context.' },
    ],
    sectorsPt: ['Clínicas e consultórios', 'Imobiliárias', 'E-commerce', 'Restaurantes', 'Academias', 'Escritórios', 'Educação', 'Varejo'],
    sectorsEn: ['Clinics', 'Real estate', 'E-commerce', 'Restaurants', 'Gyms', 'Offices', 'Education', 'Retail'],
    ctaPt: 'Quer um assistente virtual para seu negócio?',
    ctaEn: 'Want a virtual assistant for your business?',
    metricsPt: [
      { value: '24/7', label: 'Disponibilidade' },
      { value: '< 3s', label: 'Tempo de resposta' },
      { value: '95%', label: 'Resolução automática' },
      { value: '40%', label: 'Mais conversões' },
    ],
    metricsEn: [
      { value: '24/7', label: 'Availability' },
      { value: '< 3s', label: 'Response time' },
      { value: '95%', label: 'Auto resolution' },
      { value: '40%', label: 'More conversions' },
    ],
    processPt: [
      { title: 'Briefing', desc: 'Entendemos seu negócio, tom de voz e objetivos do chatbot.' },
      { title: 'Base de conhecimento', desc: 'Treinamos a IA com informações do seu negócio, FAQ e catálogo.' },
      { title: 'Desenvolvimento', desc: 'Construímos o bot com fluxos inteligentes e integração com seus sistemas.' },
      { title: 'Lançamento', desc: 'Ativamos no WhatsApp/site, monitoramos e ajustamos conforme feedback.' },
    ],
    processEn: [
      { title: 'Briefing', desc: 'We understand your business, tone of voice and chatbot goals.' },
      { title: 'Knowledge base', desc: 'We train the AI with your business info, FAQ and catalog.' },
      { title: 'Development', desc: 'We build the bot with smart flows and integration with your systems.' },
      { title: 'Launch', desc: 'We activate on WhatsApp/website, monitor and adjust based on feedback.' },
    ],
    plansPt: [
      { name: 'Básico', subtitle: 'FAQ automatizado', price: 'R$ 997', period: 'setup + R$ 197/mês', features: ['Chatbot para WhatsApp ou site', 'Até 50 perguntas treinadas', 'Respostas automáticas 24/7', 'Escalação para humano', 'Relatórios mensais'] },
      { name: 'Inteligente', subtitle: 'IA com contexto', price: 'R$ 1.997', period: 'setup + R$ 397/mês', features: ['Tudo do plano Básico', 'IA com RAG (base de conhecimento)', 'Qualificação automática de leads', 'Agendamento via Google Calendar', 'Integração com CRM', 'Multi-idioma PT/EN'], highlight: true },
      { name: 'Autônomo', subtitle: 'Vendedor digital completo', price: 'R$ 3.497', period: 'setup + R$ 697/mês', features: ['Tudo do plano Inteligente', 'Vendas e pedidos pelo chat', 'Integração com pagamento (PIX)', 'Análise de sentimento', 'Dashboard em tempo real', 'Gerente de conta dedicado'] },
    ],
    plansEn: [
      { name: 'Basic', subtitle: 'Automated FAQ', price: 'R$ 997', period: 'setup + R$ 197/mo', features: ['Chatbot for WhatsApp or website', 'Up to 50 trained questions', '24/7 automatic responses', 'Human escalation', 'Monthly reports'] },
      { name: 'Smart', subtitle: 'AI with context', price: 'R$ 1,997', period: 'setup + R$ 397/mo', features: ['Everything in Basic', 'AI with RAG (knowledge base)', 'Automatic lead qualification', 'Google Calendar scheduling', 'CRM integration', 'Multi-language PT/EN'], highlight: true },
      { name: 'Autonomous', subtitle: 'Complete digital seller', price: 'R$ 3,497', period: 'setup + R$ 697/mo', features: ['Everything in Smart', 'Sales and orders via chat', 'Payment integration (PIX)', 'Sentiment analysis', 'Real-time dashboard', 'Dedicated account manager'] },
    ],
  },

  'sites': {
    icon: Globe,
    titlePt: 'Sites & Landing Pages',
    titleEn: 'Websites & Landing Pages',
    subtitlePt: 'Sua presença digital com design que converte.',
    subtitleEn: 'Your digital presence with design that converts.',
    descPt: 'Desenvolvemos sites institucionais e landing pages com design exclusivo, velocidade de carregamento máxima e otimizados para aparecer no Google. Nada de templates genéricos — cada projeto é único e pensado para converter visitantes em clientes.',
    descEn: 'We develop institutional websites and landing pages with exclusive design, maximum loading speed and optimized to rank on Google. No generic templates — each project is unique and designed to convert visitors into clients.',
    benefitsPt: [
      { title: 'Design exclusivo', desc: 'Cada site é criado do zero, alinhado à identidade visual da sua marca.' },
      { title: 'Velocidade máxima', desc: 'Sites ultrarrápidos que carregam em menos de 2 segundos.' },
      { title: 'SEO otimizado', desc: 'Estrutura e conteúdo pensados para ranquear nas primeiras posições do Google.' },
      { title: 'Mobile first', desc: 'Design responsivo que funciona perfeitamente em qualquer dispositivo.' },
      { title: 'Formulários inteligentes', desc: 'Captação de leads com formulários que integram diretamente com seu CRM ou WhatsApp.' },
      { title: 'Painel de gestão', desc: 'Atualize textos, fotos e informações sem precisar de um programador.' },
    ],
    benefitsEn: [
      { title: 'Exclusive design', desc: 'Each site is built from scratch, aligned with your brand identity.' },
      { title: 'Maximum speed', desc: 'Ultra-fast sites that load in under 2 seconds.' },
      { title: 'Optimized SEO', desc: 'Structure and content designed to rank in Google\'s top positions.' },
      { title: 'Mobile first', desc: 'Responsive design that works perfectly on any device.' },
      { title: 'Smart forms', desc: 'Lead capture with forms that integrate directly with your CRM or WhatsApp.' },
      { title: 'Management panel', desc: 'Update texts, photos and information without needing a developer.' },
    ],
    sectorsPt: ['Restaurantes', 'Clínicas', 'Escritórios', 'Lojas', 'Academias', 'Salões de beleza', 'Construtoras', 'Startups', 'Profissionais liberais'],
    sectorsEn: ['Restaurants', 'Clinics', 'Offices', 'Shops', 'Gyms', 'Beauty salons', 'Construction', 'Startups', 'Freelancers'],
    ctaPt: 'Quer um site que realmente converte?',
    ctaEn: 'Want a website that really converts?',
    metricsPt: [
      { value: '8+', label: 'Segmentos atendidos' },
      { value: '< 48h', label: 'Entrega rápida' },
      { value: '100%', label: 'Personalizado' },
      { value: 'A+', label: 'Performance score' },
    ],
    metricsEn: [
      { value: '8+', label: 'Segments served' },
      { value: '< 48h', label: 'Fast delivery' },
      { value: '100%', label: 'Customized' },
      { value: 'A+', label: 'Performance score' },
    ],
    processPt: [
      { title: 'Briefing', desc: 'Entendemos seu negócio, público e objetivos. Definimos escopo e prazo.' },
      { title: 'Design', desc: 'Criamos o design exclusivo alinhado com a identidade da sua marca.' },
      { title: 'Desenvolvimento', desc: 'Construímos com tecnologia de ponta e velocidade máxima.' },
      { title: 'Entrega', desc: 'Publicamos, treinamos e mantemos tudo funcionando.' },
    ],
    processEn: [
      { title: 'Briefing', desc: 'We understand your business, audience and goals. Define scope and timeline.' },
      { title: 'Design', desc: 'We create the exclusive design aligned with your brand identity.' },
      { title: 'Development', desc: 'We build with cutting-edge technology and maximum speed.' },
      { title: 'Delivery', desc: 'We publish, train and keep everything running.' },
    ],
    plansPt: [
      { name: 'Essencial', subtitle: 'Presença online profissional', price: 'R$ 1.497', period: 'setup + R$ 149/mês', features: ['Página responsiva otimizada', 'Design premium personalizado', 'Galeria de fotos', 'WhatsApp flutuante', 'Certificado SSL', 'Hospedagem inclusa', 'Formulário de contato'] },
      { name: 'Profissional', subtitle: 'Site completo com funcionalidades', price: 'R$ 2.897', period: 'setup + R$ 249/mês', features: ['Tudo do Essencial', 'Múltiplas páginas', 'Cardápio/catálogo interativo', 'SEO avançado', 'Blog integrado', 'Google Maps', 'Modo claro/escuro'], highlight: true },
      { name: 'Premium', subtitle: 'E-commerce e integrações', price: 'R$ 4.497', period: 'setup + R$ 349/mês', features: ['Tudo do Profissional', 'E-commerce completo', 'Pagamento PIX + Cartão', 'Área do cliente', 'Gestão de pedidos', 'Multi-idioma', 'Design 100% exclusivo'] },
    ],
    plansEn: [
      { name: 'Essential', subtitle: 'Professional online presence', price: 'R$ 1,497', period: 'setup + R$ 149/mo', features: ['Optimized responsive page', 'Custom premium design', 'Photo gallery', 'Floating WhatsApp', 'SSL certificate', 'Hosting included', 'Contact form'] },
      { name: 'Professional', subtitle: 'Full site with features', price: 'R$ 2,897', period: 'setup + R$ 249/mo', features: ['Everything in Essential', 'Multiple pages', 'Interactive menu/catalog', 'Advanced SEO', 'Integrated blog', 'Google Maps', 'Light/dark mode'], highlight: true },
      { name: 'Premium', subtitle: 'E-commerce and integrations', price: 'R$ 4,497', period: 'setup + R$ 349/mo', features: ['Everything in Professional', 'Full e-commerce', 'PIX + Card payment', 'Client area', 'Order management', 'Multi-language', '100% exclusive design'] },
    ],
  },

  'dashboards': {
    icon: LayoutDashboard,
    titlePt: 'Dashboards & BI',
    titleEn: 'Dashboards & BI',
    subtitlePt: 'Seus números em tempo real, de forma visual e clara.',
    subtitleEn: 'Your numbers in real time, visually and clearly.',
    descPt: 'Criamos painéis interativos que transformam dados complexos em visualizações claras e acionáveis. Acompanhe vendas, finanças, operações e KPIs do seu negócio em tempo real, de qualquer dispositivo.',
    descEn: 'We create interactive panels that transform complex data into clear, actionable visualizations. Track sales, finances, operations and KPIs of your business in real time, from any device.',
    benefitsPt: [
      { title: 'Visão em tempo real', desc: 'Dados atualizados automaticamente para decisões rápidas e precisas.' },
      { title: 'Design intuitivo', desc: 'Painéis visuais que qualquer pessoa da equipe consegue entender.' },
      { title: 'Múltiplas fontes', desc: 'Conectamos dados de planilhas, ERPs, bancos, APIs e sistemas legados.' },
      { title: 'Alertas automáticos', desc: 'Notificações quando indicadores saem da faixa esperada.' },
      { title: 'Acesso mobile', desc: 'Consulte seus dados de qualquer lugar, no celular ou tablet.' },
      { title: 'Relatórios exportáveis', desc: 'Exporte relatórios em PDF ou Excel para apresentações e reuniões.' },
    ],
    benefitsEn: [
      { title: 'Real-time view', desc: 'Automatically updated data for fast and accurate decisions.' },
      { title: 'Intuitive design', desc: 'Visual panels that anyone on the team can understand.' },
      { title: 'Multiple sources', desc: 'We connect data from spreadsheets, ERPs, banks, APIs and legacy systems.' },
      { title: 'Automatic alerts', desc: 'Notifications when indicators go out of expected range.' },
      { title: 'Mobile access', desc: 'Check your data from anywhere, on phone or tablet.' },
      { title: 'Exportable reports', desc: 'Export reports in PDF or Excel for presentations and meetings.' },
    ],
    sectorsPt: ['Financeiro', 'Varejo', 'Logística', 'Marketing', 'Saúde', 'Indústria', 'Contabilidade', 'Educação'],
    sectorsEn: ['Finance', 'Retail', 'Logistics', 'Marketing', 'Healthcare', 'Manufacturing', 'Accounting', 'Education'],
    ctaPt: 'Quer ver seus dados de forma clara?',
    ctaEn: 'Want to see your data clearly?',
    metricsPt: [
      { value: 'Real-time', label: 'Dados ao vivo' },
      { value: '∞', label: 'Fontes integráveis' },
      { value: '< 5d', label: 'Primeira entrega' },
      { value: '100%', label: 'Customizado' },
    ],
    metricsEn: [
      { value: 'Real-time', label: 'Live data' },
      { value: '∞', label: 'Integrable sources' },
      { value: '< 5d', label: 'First delivery' },
      { value: '100%', label: 'Customized' },
    ],
    processPt: [
      { title: 'Levantamento', desc: 'Identificamos quais dados e KPIs são relevantes pro seu negócio.' },
      { title: 'Integração', desc: 'Conectamos suas fontes de dados — planilhas, ERPs, bancos, APIs.' },
      { title: 'Design', desc: 'Criamos visualizações claras e intuitivas com a sua marca.' },
      { title: 'Entrega', desc: 'Painel publicado, equipe treinada e alertas configurados.' },
    ],
    processEn: [
      { title: 'Assessment', desc: 'We identify which data and KPIs are relevant to your business.' },
      { title: 'Integration', desc: 'We connect your data sources — spreadsheets, ERPs, databases, APIs.' },
      { title: 'Design', desc: 'We create clear and intuitive visualizations with your brand.' },
      { title: 'Delivery', desc: 'Dashboard published, team trained and alerts configured.' },
    ],
    plansPt: [
      { name: 'Operacional', subtitle: 'Um dashboard essencial', price: 'R$ 1.297', period: 'setup + R$ 197/mês', features: ['1 dashboard interativo', 'Até 3 fontes de dados', 'Atualização automática', 'Acesso mobile', 'Exportação em PDF', 'Suporte por WhatsApp'] },
      { name: 'Gerencial', subtitle: 'Visão completa do negócio', price: 'R$ 2.497', period: 'setup + R$ 397/mês', features: ['Até 5 dashboards', 'Fontes ilimitadas', 'Alertas automáticos', 'KPIs personalizados', 'Relatórios agendados', 'Suporte prioritário'], highlight: true },
      { name: 'Estratégico', subtitle: 'BI completo com IA', price: 'R$ 4.997', period: 'setup + R$ 697/mês', features: ['Dashboards ilimitados', 'Análise preditiva com IA', 'Integração com BI tools', 'API de dados', 'White-label', 'Gerente de conta dedicado'] },
    ],
    plansEn: [
      { name: 'Operational', subtitle: 'One essential dashboard', price: 'R$ 1,297', period: 'setup + R$ 197/mo', features: ['1 interactive dashboard', 'Up to 3 data sources', 'Automatic updates', 'Mobile access', 'PDF export', 'WhatsApp support'] },
      { name: 'Managerial', subtitle: 'Complete business view', price: 'R$ 2,497', period: 'setup + R$ 397/mo', features: ['Up to 5 dashboards', 'Unlimited sources', 'Automatic alerts', 'Custom KPIs', 'Scheduled reports', 'Priority support'], highlight: true },
      { name: 'Strategic', subtitle: 'Full BI with AI', price: 'R$ 4,997', period: 'setup + R$ 697/mo', features: ['Unlimited dashboards', 'Predictive AI analysis', 'BI tools integration', 'Data API', 'White-label', 'Dedicated account manager'] },
    ],
  },

  'consultoria-ia': {
    icon: BrainCircuit,
    titlePt: 'Consultoria em IA',
    titleEn: 'AI Consulting',
    subtitlePt: 'Estratégia para implementar IA onde realmente importa.',
    subtitleEn: 'Strategy to implement AI where it really matters.',
    descPt: 'Fazemos um diagnóstico completo da sua operação para identificar onde a inteligência artificial pode gerar mais impacto. Criamos um roadmap prático, selecionamos as ferramentas certas e implementamos soluções sob medida — sem hype, com resultado.',
    descEn: 'We perform a complete diagnosis of your operation to identify where artificial intelligence can generate the most impact. We create a practical roadmap, select the right tools and implement tailored solutions — no hype, just results.',
    benefitsPt: [
      { title: 'Diagnóstico operacional', desc: 'Mapeamos seus processos e identificamos gargalos e oportunidades de automação.' },
      { title: 'Roadmap de IA', desc: 'Plano prático com prioridades, cronograma e investimento estimado.' },
      { title: 'Seleção de ferramentas', desc: 'Escolhemos as melhores tecnologias para cada caso, sem viés de fornecedor.' },
      { title: 'Implementação guiada', desc: 'Acompanhamos a implementação do início ao fim com suporte técnico contínuo.' },
      { title: 'Treinamento de equipe', desc: 'Capacitamos seu time para operar e evoluir as soluções com autonomia.' },
      { title: 'Métricas de resultado', desc: 'Definimos KPIs claros para medir o retorno real de cada implementação.' },
    ],
    benefitsEn: [
      { title: 'Operational diagnosis', desc: 'We map your processes and identify bottlenecks and automation opportunities.' },
      { title: 'AI roadmap', desc: 'Practical plan with priorities, timeline and estimated investment.' },
      { title: 'Tool selection', desc: 'We choose the best technologies for each case, without vendor bias.' },
      { title: 'Guided implementation', desc: 'We follow the implementation from start to finish with continuous technical support.' },
      { title: 'Team training', desc: 'We enable your team to operate and evolve solutions autonomously.' },
      { title: 'Result metrics', desc: 'We define clear KPIs to measure the real return of each implementation.' },
    ],
    sectorsPt: ['Qualquer setor', 'Escritórios', 'Indústria', 'Varejo', 'Saúde', 'Financeiro', 'Logística', 'Educação', 'Startups'],
    sectorsEn: ['Any industry', 'Offices', 'Manufacturing', 'Retail', 'Healthcare', 'Finance', 'Logistics', 'Education', 'Startups'],
    ctaPt: 'Quer descobrir como IA pode ajudar seu negócio?',
    ctaEn: 'Want to discover how AI can help your business?',
    metricsPt: [
      { value: '40%', label: 'Redução de custos' },
      { value: '3x', label: 'Mais produtividade' },
      { value: '< 30d', label: 'Primeiro resultado' },
      { value: '100%', label: 'Personalizado' },
    ],
    metricsEn: [
      { value: '40%', label: 'Cost reduction' },
      { value: '3x', label: 'More productivity' },
      { value: '< 30d', label: 'First results' },
      { value: '100%', label: 'Customized' },
    ],
    processPt: [
      { title: 'Diagnóstico', desc: 'Mapeamos seus processos e identificamos onde IA gera mais impacto.' },
      { title: 'Roadmap', desc: 'Criamos um plano prático com prioridades, custos e cronograma.' },
      { title: 'Implementação', desc: 'Selecionamos ferramentas e implementamos com acompanhamento contínuo.' },
      { title: 'Evolução', desc: 'Treinamos a equipe e definimos métricas de sucesso.' },
    ],
    processEn: [
      { title: 'Diagnosis', desc: 'We map your processes and identify where AI generates the most impact.' },
      { title: 'Roadmap', desc: 'We create a practical plan with priorities, costs and timeline.' },
      { title: 'Implementation', desc: 'We select tools and implement with continuous monitoring.' },
      { title: 'Evolution', desc: 'We train the team and define success metrics.' },
    ],
    plansPt: [
      { name: 'Diagnóstico', subtitle: 'Mapeamento + roadmap', price: 'R$ 1.997', period: 'projeto', features: ['Diagnóstico operacional completo', 'Mapeamento de processos', 'Roadmap de IA priorizado', 'Análise de ROI estimado', 'Relatório executivo', 'Reunião de apresentação'] },
      { name: 'Implementação', subtitle: 'Diagnóstico + execução + acompanhamento', price: 'R$ 4.997', period: 'setup + R$ 497/mês', features: ['Tudo do Diagnóstico', 'Implementação de até 3 soluções de IA', 'Seleção e configuração de ferramentas', 'Integrações com sistemas existentes', 'Treinamento da equipe', 'Suporte e manutenção mensal contínua'], highlight: true },
      { name: 'Transformação', subtitle: 'Parceria contínua', price: 'Sob consulta', period: '', features: ['Tudo do Implementação', 'Consultoria estratégica mensal', 'Implementações ilimitadas', 'Acesso a novas tecnologias', 'Gerente de inovação dedicado', 'KPIs e relatórios de impacto'] },
    ],
    plansEn: [
      { name: 'Diagnosis', subtitle: 'Mapping + roadmap', price: 'R$ 1,997', period: 'project', features: ['Complete operational diagnosis', 'Process mapping', 'Prioritized AI roadmap', 'Estimated ROI analysis', 'Executive report', 'Presentation meeting'] },
      { name: 'Implementation', subtitle: 'Diagnosis + execution + ongoing support', price: 'R$ 4,997', period: 'setup + R$ 497/mo', features: ['Everything in Diagnosis', 'Implementation of up to 3 AI solutions', 'Tool selection and configuration', 'Integration with existing systems', 'Team training', 'Ongoing monthly support and maintenance'], highlight: true },
      { name: 'Transformation', subtitle: 'Ongoing partnership', price: 'Custom', period: '', features: ['Everything in Implementation', 'Monthly strategic consulting', 'Unlimited implementations', 'Access to new technologies', 'Dedicated innovation manager', 'KPIs and impact reports'] },
    ],
  },
};
